services:
  database:
    build:
      context: BackCap_SERVER/Db/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: BackCap_WEB/Web/
      target: builder
    ports:
      - 4200:4200
  server:
    build:
      context: BackCap_SERVER/Server/
    ports:
      - 5056:5056
    depends_on:
      database:
        condition: service_healthy